required-version = ">=0.13.0"
target-version = "py310"
line-length = 100

exclude = [
  ".git",
  "venv",
  ".venv",
  "__pycache__",
  "build",
  "dist",
  "models",
  "data",
  "notebooks",
  "scripts",
  ".ruff_cache",
]

force-exclude = false

select = [
  "E",
  "F",
  "I",
  "UP",
  "B",
  "SIM",
  "S",
  "C90",
  "D",
  "ANN",
  "ASYNC",
]

ignore = [
  "D107"
]

extend-ignore = []

[per-file-ignores]
"scripts/*" = ["D", "C90", "E501"]
"notebooks/*" = ["D", "C90", "E501"]
"tests/*" = ["E501", "D"]
"**/__init__.py" = ["F401", "E402"]

[mccabe]
max-complexity = 10

[pydocstyle]
convention = "google"

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
docstring-code-format = true
docstring-code-line-length = 80
[flake8-annotations]
allow-star-arg-any = false
mypy-init-return = true
suppress-dummy-args = true
